import { videoType } from "./types";

export const branches = [
    "Сфинктериона",
    "Отряда солнца",
    "Талалы",
    "Вампирская",
    "Януса",
    "Дракона",
    "Ларисы"
];

export const episodes: videoType[] = [
    {
        number: 1,
        name: "Башня Колдуна",
        branch: [branches[0], branches[1]],
        members: ['Екатерина Варнава', 'Никита Кукушкин'],
        desc: "Первое приключение в рамках этого шоу, что еще сказать? Пора знакомиться с этой прекрасной вселенной",
        img: "https://img.youtube.com/vi/bvSC_9hWp0E/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=bvSC_9hWp0E",
        isFiller: false,
    }, 
    {
        number: 2,
        name: "Новогоднее приключение",
        branch: [branches[1]],
        members: ['Данила Поперечный', 'Мария Миногарова', 'Никита Кукушкин'],
        desc: "Филлерное новогоднее приключение, где мы впервые знакомимся с Цисгендием. Веселый новогодний выпуск с фееричными выходками Кукушкина.",
        img: "https://img.youtube.com/vi/XqMe7zUzLuI/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=XqMe7zUzLuI",
        isFiller: true,
    },
    {
        number: 3,
        name: "Пещера кобольдов",
        branch: [],
        members: ['Тимур Каргинов', 'Юля Ахмедова'],
        desc: "Разнообразная команда героев пытается помочь бедным селянам избавиться от кобольдов",
        img: "https://img.youtube.com/vi/WfUzqXhiKy8/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=WfUzqXhiKy8",
        isFiller: true,
    },
    {
        number: 4,
        name: "Дворец лорда Властона",
        branch: [branches[2]],
        members: ['Илья Соболев', 'Никита Кукушкин'],
        desc: "Первое прямое столкновение участников с лордом Властоном. Немного хаотичное, смешное приключение с Пахомом",
        img: "https://img.youtube.com/vi/6sZbmjT1NxU/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=6sZbmjT1NxU",
        isFiller: false,
    },
    {
        number: 5,
        name: "Шахты Фогельнест",
        branch: [branches[0]],
        members: ['Гарик Харламов', 'Денис Кукояка'],
        desc: "Герои Сфинктерион и Пэлиас пытаются сбежать из каторжного лагеря при помощи своих сообщников",
        img: "https://img.youtube.com/vi/eUvNxxRIO7Y/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=eUvNxxRIO7Y",
        isFiller: true,
    },
    {
        number: 6,
        name: "Адский поезд",
        branch: [branches[2]],
        members: ['Илья Соболев', 'Варвара Шмыкова', 'Никита Кукушкин'],
        desc: "Герои пытаются выбраться с адского поезда. Тот самый выпуск, где Соболеву дважды порвали футболку",
        img: "https://img.youtube.com/vi/NtwgMWhABAs/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=NtwgMWhABAs",
        isFiller: false,
    },
    {
        number: 7,
        name: 'Ночь в таверне "Кайф"',
        branch: [branches[1]],
        members: ['Владимир Маркони', 'Екатерина Варнава', 'Никита Кукушкин'],
        desc: "Герои пытаются разобраться со своими проблемами во время снежной бури в одинокой таверне. Получится ли у них?",
        img: "https://img.youtube.com/vi/H4xmF7lF0Ng/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=H4xmF7lF0Ng",
        isFiller: false,
    },
    {
        number: 8,
        name: "Покушение на Короля",
        branch: [branches[0], branches[4]],
        members: ['Данила Поперечный', 'Эльдар Джарахов'],
        desc: "Гвардейцы короля узнают о готовящемся покушении и пытаются его предотвратить весьма странными методами",
        img: "https://img.youtube.com/vi/crGNVtAMH7c/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=crGNVtAMH7c",
        isFiller: true,
    },
    {
        number: 9,
        name: "Человек в железной маске",
        branch: [branches[0]],
        members: ['Гарик Харламов', 'SQWOZBAB', 'Никита Кукушкин'],
        desc: "Сфинктерион узнает, что его отец все еще жив. Он собирает команду, чтобы спасти Эдварда с пиратского корабля",
        img: "https://img.youtube.com/vi/l9reQH01D-k/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=l9reQH01D-k",
        isFiller: false,
    },
    {
        number: 10,
        name: "Храм Юмора",
        branch: [branches[1], branches[2]],
        members: ['Тамби Масаев', 'Эмир Кашоков', 'Никита Кукушкин'],
        desc: "Разнообразная команда пытается отыскать своих родственников на очень странном юмористическом фестивале",
        img: "https://img.youtube.com/vi/GP6q6UskN34/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=GP6q6UskN34",
        isFiller: true,
    },
    {
        number: 11,
        name: "Оазис Шиш Кебаб",
        branch: [branches[0]],
        members: ['Сергей Орлов', 'Алла Михеева', 'Никита Кукушкин'],
        desc: "Эдвард со Сфинктерионом пытаются добыть из пустынного оазиса могущественный артефакт",
        img: "https://img.youtube.com/vi/uq4i73TjT5Y/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=uq4i73TjT5Y",
        isFiller: false,
    },
    {
        number: 12,
        name: "Бесагон - истребитель вампиров",
        branch: [branches[3]],
        members: ['Ида Галич', 'Антон Шастун', 'Денис Кукояка'],
        desc: "Первое появление вампиров в мире ПЧК. Но кто они - враги или союзники людей?",
        img: 'https://img.youtube.com/vi/ock_d9eoaqI/maxresdefault.jpg',
        url: "https://www.youtube.com/watch?v=ock_d9eoaqI",
        isFiller: true,
    },
    {
        number: 13,
        name: "Проклятые роды",
        branch: [branches[1]],
        members: ['Екатерина Варнава', 'Wylsacom', 'Никита Кукушкин'],
        desc: "Эрик Пэнисов наконец-то обзавелся ребенком. Станет он таким же проклятым, как и его родственники?",
        img: "https://img.youtube.com/vi/2kIkDOiVVUw/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=2kIkDOiVVUw",
        isFiller: false,
    },
    {
        number: 14,
        name: "Янус доставка",
        branch: [branches[1], branches[4]],
        members: ['Данила Поперечный', 'Руслан Кубик в Кубе', 'Никита Кукушкин'],
        desc: "Эрик пытается наскрести деньги семье перед праздником. Весьма незаконным способом. Очень незаконным",
        img: "https://img.youtube.com/vi/9ciFFrYYK8E/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=9ciFFrYYK8E",
        isFiller: false,
    },
    {
        number: 15,
        name: "Возвращение в Верджинвальд",
        branch: [branches[0], branches[6]],
        members: ['Сергей Мезенцев', 'SQWOZBAB', 'Никита Кукушкин'],
        desc: "Сфинктерион наконец возвращается в свои родные края, чтобы попытаться вернуть контроль над Верджинвальдом",
        img: "https://img.youtube.com/vi/_gltEGto2U4/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=_gltEGto2U4",
        isFiller: false,
    },
    {
        number: 16,
        name: "Вампиры Мёртвых топей",
        branch: [branches[3]],
        members: ['Костя Пушкин', 'Денис Кукояка', 'Никита Кукушкин'],
        desc: "Жители небольшой деревеньки могут узнать, что один из их соседей - могущественный вампир. Как поступят приехавшие к нему на юбилей сородичи?",
        img: "https://img.youtube.com/vi/iJIxr6EtT68/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=iJIxr6EtT68",
        isFiller: false,
    },
    {
        number: 17,
        name: "Демонизация",
        branch: [branches[2]],
        members: ['Ира Мягкова', 'Алексей Смирнов', 'Никита Кукушкин'],
        desc: "Пахом с небольшим отрядом демонов пытается остановить Властона от демонизации Понии",
        img: "https://img.youtube.com/vi/QqgBzPfBkj0/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=QqgBzPfBkj0",
        isFiller: true,
    },
    {
        number: 18,
        name: "Охота на младенца",
        branch: [branches[1], branches[4]],
        members: ['Антон Лапенко', 'Александр Паль'],
        desc: "София из-за ошибок мужа не знает, как защитить своего малыша от покушений разных козлов",
        img: "https://img.youtube.com/vi/QuhF09e9E_E/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=QuhF09e9E_E",
        isFiller: false,
    },
    {
        number: 19,
        name: "Час эльфийского суда",
        branch: [branches[0], branches[6]],
        members: ['Алексей Щербаков', 'Филипп Воронин'],
        desc: "Сфинктерион, став президентом, пытается заручиться поддержкой эльфов для борьбы с Властоном. Но у судьбы другие планы",
        img: "https://img.youtube.com/vi/jUyBXgLva78/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=jUyBXgLva78",
        isFiller: true,
    },
    {
        number: 20,
        name: "Вампирское возмездие",
        branch: [branches[3]],
        members: ['Антон Шастун', 'Дима Позов', 'Вика Складчикова'],
        desc: "Вампиры пытаются найти пропавшую подругу",
        img: "https://img.youtube.com/vi/bI4ELqJITzM/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=bI4ELqJITzM",
        isFiller: false,
    },
    {
        number: 21,
        name: "Судьба Властона",
        branch: [branches[0], branches[6]],
        members: ['Евгений Чебатков', 'Расул Чабдаров', 'Pimp'],
        desc: "Сфинктерион пытается выйти на мировую с лордом. Вот только получится ли?",
        img: "https://img.youtube.com/vi/YlnYBd17SWs/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=YlnYBd17SWs",
        isFiller: false,
    },
    {
        number: 22,
        name: "Отряд Солнца",
        branch: [branches[1], branches[4]],
        members: ['Екатерина Варнава', 'Александр Паль', 'Никита Кукушкин'],
        desc: "Вставшая на сторону добра семья Лестер-Пэнисовых сталкивается с заданием, которое им не по зубам",
        img: "https://img.youtube.com/vi/rmrg22uITEc/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=rmrg22uITEc",
        isFiller: false,
    },
    {
        number: 23,
        name: "Пробуждение Сосунеску",
        branch: [branches[3]],
        members: ['Илья Соболев', 'Оля Парфенюк', 'Денис Кукояка'],
        desc: "Вампиры пытаются выжить в новых реалиях, где на них охотятся не только люди. Им точно нужна поддержка кого-то могущественного",
        img: "https://img.youtube.com/vi/OH7j8SbgBJI/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=OH7j8SbgBJI",
        isFiller: true,
    },
    {
        number: 24,
        name: "Чёрный Геленбург",
        branch: [branches[0], branches[6]],
        members: ['Сергей Орлов', 'Филипп Воронин', 'Илья Куруч'],
        desc: "Сфинктерион пытается исправить ошибки своих решений в компании лучшего по мнению многих зрителей состава гостей",
        img: "https://img.youtube.com/vi/bLVwc2WfEMg/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=bLVwc2WfEMg",
        isFiller: false,
    },
    {
        number: 25,
        name: "Остров Соблазна",
        branch: [branches[2]],
        members: ['Олеся Иванченко', 'Дима Журавлёв'],
        desc: "Пахом использует полученный камень ",
        img: "https://img.youtube.com/vi/ngYbqdzpTsQ/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=ngYbqdzpTsQ",
        isFiller: false,
    },
    {
        number: 26,
        name: "Четвёртая Фабрика",
        branch: [branches[3]],
        members: ['Екатерина Варнава', 'Денис Кукояка', 'Лена Кукояка'],
        desc: "Клан Балан делает первый шаг в борьбе с верхушкой вампирского мира",
        img: "https://img.youtube.com/vi/XQecjEcXqS0/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=XQecjEcXqS0",
        isFiller: false,
    },
    {
        number: 27,
        name: "Достучаться до небес",
        branch: [branches[2]],
        members: ['Владимир Маркони', 'Женя Искандарова', 'Дэниел Барнс'],
        desc: "Невероятно важный сюжетно выпуск о жизни богов и рая. Но если вы не любите, когда постоянно друг друга перебивают или пассивно агрессируют, то смотреть не рекомендую",
        img: "https://img.youtube.com/vi/hpByQd_jpqU/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=hpByQd_jpqU",
        isFiller: false,
    },
    {
        number: 28,
        name: "Чёрное небо вампиров",
        branch: [branches[3]],
        members: ['Арсений Попов', 'Антон Шастун', 'Дмитрий Позов'],
        desc: "Клан Балан пытается помешать плану высших вампиров по завоеванию всей Понии",
        img: "https://img.youtube.com/vi/xPJ5DFEw1L0/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=xPJ5DFEw1L0",
        isFiller: false,
    },
    {
        number: 29,
        name: 'Отель "Глубокий канал"',
        branch: [branches[1], branches[4]],
        members: ['Арсений SALUKI', 'Вася Шакулин', 'SQWOZBAB'],
        desc: "Отряд Солнца дает наводку гвардейцам на личность Януса и пытается вылечить Лешу от последствий использования божественной силы",
        img: "https://img.youtube.com/vi/oflt0oNWTpQ/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=oflt0oNWTpQ",
        vkUrl: "https://vkvideo.ru/video-158117199_456239471",
        isFiller: true,
    },
    {
        number: 30,
        name: "Ультиматум Сфинктериона",
        branch: [branches[6]],
        members: ['Филипп Воронин', 'Илья Куруч', 'Александр Малой'],
        desc: "Отважная крыса узнает о намерении Сфинктериона воспользоваться беззащитным ребенком для открытия портала на небеса и пытается защитить дитя",
        img: "https://img.youtube.com/vi/Vb9GxPsLiKI/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=Vb9GxPsLiKI",
        vkUrl: "https://vkvideo.ru/video-158117199_456239509",
        isFiller: false,
    },
    {
        number: 31,
        name: "Культ Кракена",
        branch: [branches[2]],
        members: ['Слава Копейкин', 'Александра Бортич', 'Гоген Солнцев'],
        desc: "Талала еле унесла ноги с небес, как тут же попадает в западню демонов. Что она сможет им противопоставить?",
        img: "https://img.youtube.com/vi/VtE9ZAhF03E/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=VtE9ZAhF03E",
        vkUrl: "https://vkvideo.ru/video-158117199_456239575",
        isFiller: false,
    },
    {
        number: 32,
        name: "Путешествие к Нергалу",
        branch: [branches[4], branches[5]],
        members: ['Илья Сатир', 'Руслан Усачев'],
        desc: "Эльфа Дододиса шантажируют, украв его любимую сестру. Но что будет делать эльф, который почти не имеет полезных связей в столице?",
        img: "https://img.youtube.com/vi/cZrmGos4fhg/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=cZrmGos4fhg",
        vkUrl: "https://vkvideo.ru/video-158117199_456239621",
        isFiller: false,
    },
    {
        number: 33,
        name: "Зверь Фест",
        branch: [branches[3]],
        members: ['Ира Мягкова', 'Вера Котельникова', 'Слава Бустер'],
        desc: "Вампиры снова могут не бояться выходить на улицу, и оборотни сразу подкидывают им задачку - приглядеть за проведением фестиваля",
        img: "https://img.youtube.com/vi/aalb4uiuRyo/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=aalb4uiuRyo",
        vkUrl: "https://vkvideo.ru/video-158117199_456239675",
        isFiller: true,
    },
    {
        number: 34,
        name: "Пропавшая ёлочка",
        branch: [branches[3], branches[1]],
        members: ['Виктория Складчикова', 'Александр Паль', 'Борис Зелигер'],
        desc: "Новогодний семейный спешл ПЧК. Ведьма Мирамистина не может найти свою дочурку - елочку - и просит помощи у отряда Солнца",
        img: "https://img.youtube.com/vi/CrT8bkdKWVU/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=CrT8bkdKWVU",
        vkUrl: "https://vkvideo.ru/video-158117199_456239722",
        isFiller: true,
    },
    {
        number: 35,
        name: "Второй Шанс",
        branch: [branches[0]],
        members: ['Гоген Солнцев', 'Макс +100500', 'Саша Сулим'],
        desc: "После провала Сфинктерион не готов сдаваться и ищет другие варианты помочь Темному Властелину",
        img: "https://img.youtube.com/vi/aCYWh-P7bHU/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=aCYWh-P7bHU",
        vkUrl: "https://vkvideo.ru/video-158117199_456239810",
        isFiller: false,
    },
    {
        number: 36,
        name: "Руины Малестии",
        branch: [branches[6]],
        members: ['Филипп Воронин', 'Илья Куруч', 'Сергей Орлов'],
        desc: "Крыса Лариса со своей командой отступников пытается найти силу, чтобы противостоять своим врагам",
        img: "https://img.youtube.com/vi/OqBzHvxBCsg/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=OqBzHvxBCsg",
        vkUrl: "https://vkvideo.ru/video-158117199_456239870",
        isFiller: false,
    },
    {
        number: 37,
        name: "Добровольцы",
        branch: [branches[1]],
        members: ['Александр Паль', 'Вячеслав Чепурченко', 'Лев Зулькарнаев'],
        desc: "Два гениальных командира ведут свой немногочисленный отряд на верную смерть. Ладно, может, у них и что-то выйдет",
        img: "https://img.youtube.com/vi/9TmL8N5ZGFo/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=9TmL8N5ZGFo",
        vkUrl: "https://vkvideo.ru/video-158117199_456239938",
        isFiller: true,
    },
    {
        number: 38,
        name: "Возлюбленная",
        branch: [branches[2]],
        members: ['Сергей Мезенцев', 'Ян Топлес', 'Вика Чума'],
        desc: "Талала узнала кое-что очень важное на телефоне Брендона. Кажется, это поможет спасти мир с минимальными жертвами",
        img: "https://img.youtube.com/vi/bDkJlzAFKjY/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=bDkJlzAFKjY",
        vkUrl: "https://vkvideo.ru/video-158117199_456240010",
        isFiller: false,
    },
    {
        number: 39,
        name: "Кунисская пленница",
        branch: [branches[5]],
        members: ['Илья Макаров', 'Эмир Кашоков', 'Турал Натурал'],
        desc: "Дракону хочется заполучить первую дварфийскую красавицу. А дварфам не очень хочется быть сожжеными драконом",
        img: "https://img.youtube.com/vi/s0rqhh7IbX8/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=s0rqhh7IbX8",
        vkUrl: "https://vkvideo.ru/video-158117199_456240075",
        isFiller: true,
    },
    {
        number: 40,
        name: "Паспорт хорошей твари",
        branch: [branches[3]],
        members: ['Константин Пушкин', 'Александр Малой'],
        desc: "Демоны наступают, а некоторые твари встают на их сторону. Тогда как отличить хорошую тварь от плохой?",
        img: "https://img.youtube.com/vi/AFxewi5RiuY/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=AFxewi5RiuY",
        vkUrl: "https://vkvideo.ru/video-158117199_456240135",
        isFiller: false,
    },
    {
        number: 41,
        name: "Гонка за желанием",
        branch: [branches[0]],
        members: ['Евгений Чебатков', 'Асха Принц', 'Young P&H (Пимп)'],
        desc: 'У Сфинктериона проблемы. Но он вспоминает слова классика "кто сдается - тот лох", и упрямо идет к своей цели',
        img: "https://img.youtube.com/vi/6USQ969nMPI/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=6USQ969nMPI",
        vkUrl: "https://vkvideo.ru/video-158117199_456240219",
        isFiller: false,
    },
    {
        number: 42,
        name: "Чудная Долина",
        branch: [branches[2]],
        members: ['Екатерина Варнава', 'Александра Бортич', 'Слава Копейкин'],
        desc: "Талала сняла проклятие с Мелиссы, но у нее появились сомнения, поймет ли Темный Властелин свою возлюбленную спустя столько лет",
        img: "https://img.youtube.com/vi/svnG2c_HvK8/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=svnG2c_HvK8",
        vkUrl: "https://vkvideo.ru/video-158117199_456240282",
        isFiller: false,
    },
    {
        number: 43,
        name: "Груз Кристиночки",
        branch: [branches[4]],
        members: ['Илья Сатир', 'Руслан Усачев'],
        desc: "Ценный груз из зубастых игрушек, что покупала Кристиночка для лавки всякой всячины, пропал. Но она не собирается разорять дело своего брата так просто",
        img: "https://img.youtube.com/vi/pBKAMk_J0qw/maxresdefault.jpg",
        url: "https://www.youtube.com/watch?v=pBKAMk_J0qw",
        vkUrl: "https://vkvideo.ru/video-158117199_456240356",
        isFiller: true,
    },
];